name: Continuous integration

on:
  push:
    branches: ['**']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v3
      - name: Install, build site
        uses: withastro/action@v1
        with:
          node-version: 20
